# Generated by Django 5.1.2 on 2025-01-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.CharField(max_length=500)),
                ('HTU', models.CharField(max_length=500)),
                ('COO', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('skincare', 'Skincare'), ('hair&body', 'Hair & Body'), ('makeup', 'Makeup'), ('necessities', 'Necessities')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
